apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-per-branch
spec:
  generators:
    - git:
        repoURL: 'https://github.com/Sipixer/testGitOps.git'
        revision: '*'
        directories:
          - path: k8s/base/helm-chart
        branches:
          - pattern: '*'
  template:
    metadata:
      name: '{{branch}}-app'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/Sipixer/testGitOps.git'
        targetRevision: '{{branch}}'
        path: k8s/base/helm-chart
        helm:
          values: |
            branch: '{{branch}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{branch}}-ns'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
