apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "app-chart.name" . }}
    branch: {{ .Values.branch }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "app-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "app-chart.name" . }}
        branch: {{ .Values.branch }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:test"
          ports:
            - containerPort: 80
