apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app-chart.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "{{ .Values.branch }}.example.com"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "app-chart.fullname" . }}
              port:
                number: {{ .Values.service.port }}
