apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-lab
  namespace: TEST
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-lab
  template:
    metadata:
      labels:
        app: gitops-lab
    spec:
      containers:
      - name: gitops-lab
        image: ghcr.io/sipixer/gitops-lab:main
        ports:
        - containerPort: 3000
