name: CI/CD

on:
  push:
    branches:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF_NAME#refs/heads/}" | tr '[:upper:]' '[:lower:]' | tr '/' '-')
          IMAGE=ghcr.io/${{ github.repository_owner }}/gitops-lab:$BRANCH_NAME
          echo "Building $IMAGE"
          docker build -t $IMAGE ./app
          docker push $IMAGE
